### PR TITLE
Benchmark SpiderMonkey

### PR DESCRIPTION
**Pull request by sagudev**

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
This won't work as-is, `data["results"][engine].push(...)` assumes that the continuously updated JSON file already has an array entry for any given engine, which needs to be handled for newly added engines.

**Comment by jasonwilliams** [comment]
Yep this is a good point, also the format right now was to save space and not repeat the date each time, so instead it uses the position of the value to get the date (in the same position), but if we did add SM it would end up on the beginning of the chart and not with the others so there’s 2 options.

- Change the format so it’s easier to add engines (but may not be space efficient)
- Zero out all of the entries up until today for SM

long term we may need to use a database instead of ever-growing json files for this

**Comment by sagudev** [comment]
run in my fork: https://github.com/sagudev/data/actions/runs/10113797480/job/27970948587

**Comment by sagudev** [comment]
new run: https://github.com/sagudev/data/actions/runs/10114233845

**Comment by sagudev** [comment]
Everyday new zero entries are needed because it's diverging from main. Notify me before planing to merge so I can add more entries (or DIY as I allowed edits by maintainers).

**Comment by jasonwilliams** [comment]
@sagudev you're right, every day we leave this it will need updating again, from what i can see the PR looks fine, I think we can merge this.

Thank you for the effort, one thing i would love to see is an option to hide v8/sm from the charts but that can be added in a follow up by someone. Issue here: https://github.com/boa-dev/data/issues/6

**Comment by sagudev** [comment]
@jasonwilliams can you also trigger workflow run, so the data gets updated.

**Comment by jasonwilliams** [comment]
I've ran it but this will need to be merged before we can see it on the site:
https://github.com/boa-dev/boa-dev.github.io/pull/165

**Pull request merged**
